/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, THIS FILE ABLE TO UPDATE by DEVELOPER inside the existing functions.
 * Author: ThanhNV22, FPT Software
*/
#include "STATE_ID_SCREEN_A.h"

void SCREEN_A_Entry(QVariant msg, uchar source) {

}

void SCREEN_A_Exit(QVariant msg, uchar source) {

}

void BTN_A_MSG(QVariant msg, uchar source) {

}

void EVT_SCREEN_A_BUTTON_YYY_CLICKED_MSG(QVariant msg, uchar source) {

}

void EVT_SCREEN_A_BUTTON_XXX_CLICKED_MSG(QVariant msg, uchar source) {

}

