/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, THIS FILE ABLE TO UPDATE by DEVELOPER inside the existing functions.
 * Author: ThanhNV22, FPT Software
*/
#include "STATE_ID_POPUP_B.h"

void POPUP_B_Entry(QVariant msg, uchar source) {

}

void POPUP_B_Exit(QVariant msg, uchar source) {

}

void EVT_POPUP_B_BUTTON_XXX_CLICKED_MSG(QVariant msg, uchar source) {

}

void EVT_POPUP_B_BUTTON_YYY_CLICKED_MSG(QVariant msg, uchar source) {

}

