/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, THIS FILE ABLE TO UPDATE by DEVELOPER inside the existing functions.
 * Author: ThanhNV22, FPT Software
*/
#include "STATE_ID_SCREEN_LOGIN_NX_CLOUD.h"

void SCREEN_LOGIN_NX_CLOUD_Entry(QVariant msg, uchar source) {

}

void SCREEN_LOGIN_NX_CLOUD_Exit(QVariant msg, uchar source) {

}

void EVT_SCREEN_LOGIN_NX_CLOUD_BUTTON_NEXT_CLICKED_MSG(QVariant msg, uchar source) {

}

void EVT_SCREEN_LOGIN_NX_CLOUD_BUTTON_BACK_CLICKED_MSG(QVariant msg, uchar source) {

}

