/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, THIS FILE ABLE TO UPDATE by DEVELOPER inside the existing functions.
 * Author: ThanhNV22, FPT Software
*/
#include "STATE_ID_ROOT.h"

void ROOT_Entry(QVariant msg, uchar source) {

}

void ROOT_Exit(QVariant msg, uchar source) {

}

void EVT_BLK_TO_SCREEN_A_MSG(QVariant msg, uchar source) {

}

void EVT_BLK_TO_POPUP_B_MSG(QVariant msg, uchar source) {

}

