/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, THIS FILE ABLE TO UPDATE by DEVELOPER inside the existing functions.
 * Author: ThanhNV22, FPT Software
*/
#include "STATE_ID_SCREEN_B.h"
#include <QDebug>
#include "mainmodelserver.h"
#include "editservermodel.h"
#include "appengine.h"
void SCREEN_B_Entry(QVariant msg, uchar source) {

}

void SCREEN_B_Exit(QVariant msg, uchar source) {

}

void EVT_SCREEN_B_BUTTON_SERVER_CLICKED_MSG(QVariant msg, uchar source) {

}

void EVT_SCREEN_B_BUTTON_YYY_CLICKED_MSG(QVariant msg, uchar source) {

}

void EVT_SCREEN_B_BUTTON_EDIT_SERVER_CLICKED_MSG(QVariant msg, uchar source){
    qDebug() << __func__;
//    qDebug() << msg;
    bool ok;
    //qDebug() <<  msg.value<QString>();
    qintptr address = msg.value<QString>().toLongLong(&ok, 16);
    if (ok) {
        modelServer* model = reinterpret_cast<modelServer*>(address);
        qDebug() << model->name();
        qDebug() << "ok";
        editServerItem* item = new editServerItem(model->name(), model->server(), model->username(), model->password(), model->connect(), model->login());
        EditServerModel *editmodel = AppEngine::getInstance()->editModel();
        editmodel->addServer(item);
        //editServerModel.addServer(editModel);
        qDebug() << __func__ << QString::number(reinterpret_cast<quintptr>(AppEngine::getInstance()->editModel()), 16);
    }
    else {
        qDebug() << "not ok";
    }


}
