/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, THIS FILE ABLE TO UPDATE by DEVELOPER inside the existing functions.
 * Author: ThanhNV22, FPT Software
*/
#include "STATE_ID_POPUP_edit_server.h"

void POPUP_edit_server_Entry(QVariant msg, uchar source) {

}

void POPUP_edit_server_Exit(QVariant msg, uchar source) {

}

void EVT_POPUP_edit_server_BUTTON_BACK_CLICKED_MSG(QVariant msg, uchar source) {

}

void EVT_POPUP_edit_server_BUTTON_DELETE_CLICKED_MSG(QVariant msg, uchar source) {

}

void EVT_POPUP_edit_server_BUTTON_CONNECT_CLICKED_MSG(QVariant msg, uchar source) {

}

