/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, DON'T TRY TO CHANGE ANYTHING OF THIS FILE.
 * Author: ThanhNV22, FPT Software
*/
#ifndef STATE_ID_POPUP_A_H
#define STATE_ID_POPUP_A_H

#include "QAppFramework.h"
#include "QQuickViewer.h"
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void POPUP_A_Exit(QVariant msg, uchar source);

#endif // STATE_ID_POPUP_A_H
