/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, DON'T TRY TO CHANGE ANYTHING OF THIS FILE.
 * Author: ThanhNV22, FPT Software
*/
#ifndef STATE_ID_SCREEN_A_H
#define STATE_ID_SCREEN_A_H

#include "QAppFramework.h"
#include "QQuickViewer.h"
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void SCREEN_A_Entry(QVariant msg, uchar source);
void SCREEN_A_Exit(QVariant msg, uchar source);
void BTN_A_MSG(QVariant msg, uchar source);
void EVT_SCREEN_A_BUTTON_YYY_CLICKED_MSG(QVariant msg, uchar source);
void EVT_SCREEN_A_BUTTON_XXX_CLICKED_MSG(QVariant msg, uchar source);

#endif // STATE_ID_SCREEN_A_H
