/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, DON'T TRY TO CHANGE ANYTHING OF THIS FILE.
 * Author: ThanhNV22, FPT Software
*/
#ifndef STATE_ID_POPUP_B_H
#define STATE_ID_POPUP_B_H

#include "QAppFramework.h"
#include "QQuickViewer.h"
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void POPUP_B_Entry(QVariant msg, uchar source);
void POPUP_B_Exit(QVariant msg, uchar source);
void EVT_POPUP_B_BUTTON_XXX_CLICKED_MSG(QVariant msg, uchar source);
void EVT_POPUP_B_BUTTON_YYY_CLICKED_MSG(QVariant msg, uchar source);

#endif // STATE_ID_POPUP_B_H
