/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, DON'T TRY TO CHANGE ANYTHING OF THIS FILE.
 * Author: ThanhNV22, FPT Software
*/
#ifndef STATE_ID_POPUP_edit_server_H
#define STATE_ID_POPUP_edit_server_H

#include "QAppFramework.h"
#include "QQuickViewer.h"
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void POPUP_edit_server_Entry(QVariant msg, uchar source);
void POPUP_edit_server_Exit(QVariant msg, uchar source);
void EVT_POPUP_edit_server_BUTTON_CONNECT_CLICKED_MSG(QVariant msg, uchar source);
void EVT_POPUP_edit_server_BUTTON_DELETE_CLICKED_MSG(QVariant msg, uchar source);
void EVT_POPUP_edit_server_BUTTON_BACK_CLICKED_MSG(QVariant msg, uchar source);


#endif // STATE_ID_POPUP_B_H
