/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, DON'T TRY TO CHANGE ANYTHING OF THIS FILE.
 * Author: ThanhNV22, FPT Software
*/
#ifndef STATE_ID_ROOT_H
#define STATE_ID_ROOT_H

#include "QAppFramework.h"
#include "QQuickViewer.h"
#include "ViewsDefines.h"
#include "ViewsEnums.h"

void ROOT_Entry(QVariant msg, uchar source);
void ROOT_Exit(QVariant msg, uchar source);
void EVT_BLK_TO_SCREEN_A_MSG(QVariant msg, uchar source);
void EVT_BLK_TO_POPUP_B_MSG(QVariant msg, uchar source);

#endif // STATE_ID_ROOT_H
