/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, THIS FILE ABLE TO UPDATE by DEVELOPER inside the existing functions.
 * Author: ThanhNV22, FPT Software
*/
#ifndef VIEWSDEFINES_H
#define VIEWSDEFINES_H

#define POPUP_A                 "qrc:/QML_RESOURCES/Qml/Popups/Popup_A.qml"
#define POPUP_B                 "qrc:/QML_RESOURCES/Qml/Popups/Popup_B.qml"
#define POPUP_edit_server       "qrc:/QML_RESOURCES/Qml/Popups/Popup_edit_server.qml"
#define ROOT                    ""
#define SCREEN_A                "qrc:/QML_RESOURCES/Qml/Screens/SCREEN_A.qml"
#define SCREEN_B                "qrc:/QML_RESOURCES/Qml/Screens/SCREEN_B.qml"
#define SCREEN_LOGIN_NX_CLOUD   "qrc:/QML_RESOURCES/Qml/Screens/SCREEN_LOGIN_NX_CLOUD.qml"

#endif // VIEWSDEFINES_H
