/*
 * This file was generated by Mr. ThanhNV22 via his tool.
 * This is an auto-generated file, DON'T TRY TO CHANGE ANYTHING OF THIS FILE.
 * Author: ThanhNV22, FPT Software
*/
#ifndef VIEWSTATES_H
#define VIEWSTATES_H

#include "ViewsDefines.h"
#include "ViewsEnums.h"
#include "STATE_ID_POPUP_A.h"
#include "STATE_ID_POPUP_B.h"
#include "STATE_ID_POPUP_edit_server.h"
#include "STATE_ID_ROOT.h"
#include "STATE_ID_SCREEN_A.h"
#include "STATE_ID_SCREEN_B.h"
#include "STATE_ID_SCREEN_LOGIN_NX_CLOUD.h"

#endif // VIEWSTATES_H
